version: '3.3'

services:
  nectia-frontend:
    build: .
    depends_on:
      - nectia-backend
    restart: always
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    ports:
      - "3000:3000"
    volumes:
      - .:/src